#!/usr/bin/env bash
# Pull the real macOS app icons off this Mac into assets/dock/, then point the
# dock at them. Run on macOS: npm run icons:mac
#
# Apple's icon artwork stays on your machine — assets/dock/ is gitignored, so
# nothing copyrighted gets committed. Anyone who clones the repo without running
# this falls back to the drawn icon set in src/components/DockIcons.tsx.
set -uo pipefail

if [[ "$(uname)" != "Darwin" ]]; then
  echo "This script only runs on macOS (it reads icons out of installed .app bundles)."
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/assets/dock"
SIZE=256
CORE="/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources"
mkdir -p "$OUT"

# id|candidate paths (first that exists wins), ; separated
ENTRIES=(
  "finder|/System/Library/CoreServices/Finder.app"
  "launchpad|/System/Applications/Launchpad.app;/Applications/Launchpad.app"
  "chrome|/Applications/Google Chrome.app"
  "safari|/Applications/Safari.app;/System/Applications/Safari.app"
  "messages|/System/Applications/Messages.app"
  "mail|/System/Applications/Mail.app"
  "maps|/System/Applications/Maps.app"
  "photos|/System/Applications/Photos.app"
  "facetime|/System/Applications/FaceTime.app"
  "phone|/System/Applications/Phone.app"
  "calendar|/System/Applications/Calendar.app"
  "contacts|/System/Applications/Contacts.app"
  "reminders|/System/Applications/Reminders.app"
  "notes|/System/Applications/Notes.app"
  "appletv|/System/Applications/TV.app"
  "music|/System/Applications/Music.app"
  "podcasts|/System/Applications/Podcasts.app"
  "news|/System/Applications/News.app"
  "appstore|/System/Applications/App Store.app"
  "settings|/System/Applications/System Settings.app;/System/Applications/System Preferences.app"
  "textedit|/System/Applications/TextEdit.app"
  "preview|/System/Applications/Preview.app"
  "spotify|/Applications/Spotify.app"
  "folder|$CORE/GenericFolderIcon.icns"
  "document|$CORE/GenericDocumentIcon.icns"
  "trash|$CORE/TrashIcon.icns;$CORE/EmptyTrashIcon.icns"
)

# Resolve an .app (or a bare .icns) to an .icns file on disk.
resolve_icns() {
  local target="$1"
  [[ "$target" == *.icns ]] && { [[ -f "$target" ]] && echo "$target"; return; }
  [[ -d "$target" ]] || return
  local res="$target/Contents/Resources"
  local named
  named="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIconFile' "$target/Contents/Info.plist" 2>/dev/null)"
  if [[ -n "$named" ]]; then
    [[ "$named" != *.icns ]] && named="$named.icns"
    [[ -f "$res/$named" ]] && { echo "$res/$named"; return; }
  fi
  # some bundles only ship an unnamed .icns
  local first
  first="$(/usr/bin/find "$res" -maxdepth 1 -name '*.icns' -print -quit 2>/dev/null)"
  [[ -n "$first" ]] && echo "$first"
}

found=(); missing=()
for entry in "${ENTRIES[@]}"; do
  id="${entry%%|*}"
  IFS=';' read -ra paths <<< "${entry#*|}"
  icns=""
  for p in "${paths[@]}"; do
    icns="$(resolve_icns "$p")"
    [[ -n "$icns" ]] && break
  done
  if [[ -z "$icns" ]]; then
    missing+=("$id")
    continue
  fi
  if /usr/bin/sips -s format png "$icns" --out "$OUT/$id.png" -Z "$SIZE" >/dev/null 2>&1; then
    found+=("$id")
  else
    missing+=("$id")
  fi
done

# Write the manifest the app imports. Only ids we actually produced.
MANIFEST="$ROOT/src/dockAssets.ts"
{
  echo "// GENERATED by scripts/extract-mac-icons.sh — do not edit by hand."
  echo "// Run \`npm run icons:mac\` to refresh, \`npm run icons:reset\` to go back to the drawn set."
  echo "import type { ImageSourcePropType } from 'react-native';"
  echo "import type { DockGlyphId } from './components/DockIcons';"
  echo ""
  echo "export const dockAssets: Partial<Record<DockGlyphId, ImageSourcePropType>> = {"
  for id in "${found[@]}"; do
    echo "  $id: require('../assets/dock/$id.png'),"
  done
  echo "};"
} > "$MANIFEST"

echo "Extracted ${#found[@]} icons into assets/dock/"
if (( ${#missing[@]} )); then
  echo "Not installed on this Mac (keeping the drawn fallback): ${missing[*]}"
fi
echo "Restart the bundler with: npm start -- --clear"
